name: typelayer-c
dependencies:
    - base
    - text
    - bytestring
    - mtl
    - binary
    - containers
    - time
    - typelayer-common

library:
  ghc-options:
  - -threaded
  - -O0
  source-dirs: src/
tests:
  typelayer-c-test:
    main: Spec.hs
    source-dirs: src/tests
    ghc-options:
    - -threaded
    - -O0
    dependencies:
        - typelayer-c
        - typelayer-common
        - hspec
