flags: {}
system-ghc: true
resolver: lts-13.22
allow-different-user: true
extra-path:
- /usr/local/typelayer-packages/haskell/generated
packages:
- .
extra-deps:
    - vendor/typelayer-common
    - hspec-2.6.1
